version: '3.1'

services:
  properties_pg:
    image: postgres:17.2
    container_name: properties_pg
    restart: always
    environment:
      POSTGRES_DB: real_estate_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root.pass
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432